name: Deploy To Google Play

on:
  push:
    branches: [master]
  
jobs:
  build:
    name: Build Android App
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK 18
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 11
          cache: 'gradle'

      - name: Validate Gradle wrapper
        uses: gradle/actions/wrapper-validation@v3

      - name: Install deps
        run: |
          npm install yarn
          yarn install

      - name: Version Bump
        uses: chkfung/android-version-actions@v1.2.3
        with:
          gradlePath: android/app/build.gradle
          versionCode: ${{ github.run_number }}

      - name: Assemble Release Bundle
        run: |
          cd android
          ./gradlew bundleRelease
      
      - name: Sign Release
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/bundle/release
          signingKeyBase64: ${{ secrets.ANDROID_KEYSTORE }}
          keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
          alias: ${{ secrets.ANDROID_DEVS_ALIAS }}
          keyPassword: ${{ secrets.ANDROID_DEVS_ALIAS_PASSWORD }}
